Feature/add pix payment
jonatasoli/fast-ecommerce-front pull request #174
Opened 2023-12-13 18:16 UTC by felipe-dna

2024-04-03 12:56 UTC, jonatasoli commented
Relacionado a issue https://github.com/jonatasoli/fast-ecommerce-front/issues/144

2024-04-03 13:18 UTC, jonatasoli submitted a review, later dismissed
LGTM!

2024-04-05 00:02 UTC, thaismtss requested changes

2024-04-05 00:02 UTC, thaismtss commented on server/api/cart/[uuid]/payment/pix.post.ts.ts
> +import { defineEventHandler, getCookie, readBody, createError } from 'h3'
Corrigir o nome do arquivo que tá .ts.ts

2024-07-10 13:54 UTC, felipe-dna commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
👀

2024-07-17 06:57 UTC, merged