Recaptcha
jonatasoli/fast-ecommerce-front pull request #206
Opened 2024-09-03 16:10 UTC by Jpcampos123

Google's "recaptcha" feature was created in version 3.

2024-09-04 08:35 UTC, jonatasoli requested changes
O código está bom, mas tem a questão do código chumbado e também é interesasnte ter o recaptcha no cadastro.

2024-09-04 08:35 UTC, jonatasoli commented on pages/login/index.vue
> +      '6LdTEDUqAAAAAIJKc7S2PyXtqrfIDpDkrYeD54_A',
o token precisa ser recebido via variável de ambiente não fixo no código.

2024-09-04 08:35 UTC, jonatasoli commented on plugins/recaptcha.ts
> +    script.src = `https://www.google.com/recaptcha/api.js?render=6LdTEDUqAAAAAIJKc7S2PyXtqrfIDpDkrYeD54_A`
mesma coisa aquiesse código não pode estar fixo aqui.

2024-09-10 13:58 UTC, Jpcampos123 commented on pages/login/index.vue
> +      '6LdTEDUqAAAAAIJKc7S2PyXtqrfIDpDkrYeD54_A',
o código do commit vai aqui #206 
??

2024-09-11 12:14 UTC, jonatasoli commented on plugins/recaptcha.ts
> +    script.src = `https://www.google.com/recaptcha/api.js?render=6LdTEDUqAAAAAIJKc7S2PyXtqrfIDpDkrYeD54_A`
vi agora que você colocou a pr o certo é o commit olha como fica aqui embaixo:
bf36639cc1aef0d9fe737396833de51bd700893b

2024-09-11 12:15 UTC, jonatasoli commented on plugins/recaptcha.ts
> +    script.src = `https://www.google.com/recaptcha/api.js?render=6LdTEDUqAAAAAIJKc7S2PyXtqrfIDpDkrYeD54_A`
se você clicar no link vai perceber que vai diretamente no commit onde você fez a alteração.

2024-09-11 12:44 UTC, jonatasoli requested changes
Mais algumas sugestões de modificação

2024-09-11 12:44 UTC, jonatasoli commented on package.json
> +    "vitest": "^0.33.0",
precisa realmente voltar a versão do vite?

2024-09-11 12:44 UTC, jonatasoli commented on nuxt.config.ts
> +      srcSiteKey: process.env.SRC_SITE_KEY,
```suggestion
      srcSiteKey: process.env.RECAPTCHA_SECRET_KEY,
```

Você acha que assim ficaria mais explicito?

2024-09-11 12:44 UTC, jonatasoli commented on nuxt.config.ts
> +      siteKey: process.env.SITE_KEY,
```suggestion
      siteKey: process.env.RECAPTCHA_KEY,
```

2024-09-11 12:44 UTC, jonatasoli commented on pages/login/index.vue
> +  const siteKey = config.public.siteKey
```suggestion
  const recaptchaKey = config.public.RECAPTCHA_KEY
```

2024-09-11 12:44 UTC, jonatasoli commented on pages/login/index.vue
> +    const token = await grecaptcha.execute(siteKey, { action: 'submit' })
```suggestion
    const token = await grecaptcha.execute(recaptchaKey, { action: 'submit' })
```

2024-09-11 12:44 UTC, jonatasoli commented on pages/register/index.vue
> +  const siteKey = config.public.siteKey
```suggestion
  const recaptchaKey = config.public.RECAPTCHA_KEY
```

2024-09-11 12:44 UTC, jonatasoli commented on pages/register/index.vue
> +    const token = await grecaptcha.execute(siteKey, { action: 'submit' })
```suggestion
    const token = await grecaptcha.execute(recaptchaKey, { action: 'submit' })
```

2024-09-11 12:44 UTC, jonatasoli commented on plugins/recaptcha.ts
> +  const srcSiteKey = $config.public.srcSiteKey as string
```suggestion
  const recaptchaSecretKey = $config.public.RECAPTCHA_SECRET_KEY as string
```

2024-09-11 12:44 UTC, jonatasoli commented on plugins/recaptcha.ts
> +    script.src = srcSiteKey
```suggestion
    script.src = recaptchaSecretKey
```

2024-09-11 13:10 UTC, Jpcampos123 commented on pages/login/index.vue
> +      '6LdTEDUqAAAAAIJKc7S2PyXtqrfIDpDkrYeD54_A',
atualizado  commit - bf36639cc1aef0d9fe737396833de51bd700893b

2024-09-11 13:10 UTC, Jpcampos123 commented on plugins/recaptcha.ts
> +    script.src = `https://www.google.com/recaptcha/api.js?render=6LdTEDUqAAAAAIJKc7S2PyXtqrfIDpDkrYeD54_A`
atualizei commit - bf36639cc1aef0d9fe737396833de51bd700893b

2024-09-11 13:47 UTC, Jpcampos123 commented on package.json
> +    "vitest": "^0.33.0",
realmente não precisa, estava tendo alguns problemas para instalar o projeto, mas depois consegui solucionar e esqueci de voltar para a última versão, commit - 22dc09480bb0ef125e6de1a7c54f64466475b8ef

2024-09-11 13:47 UTC, Jpcampos123 commented on nuxt.config.ts
> +      srcSiteKey: process.env.SRC_SITE_KEY,
tinha deixado do jeito que o site do google sugere, mas já atualizei nesse commit - 22dc09480bb0ef125e6de1a7c54f64466475b8ef

2024-09-11 13:48 UTC, Jpcampos123 commented on nuxt.config.ts
> +      siteKey: process.env.SITE_KEY,
atualizado commit - 22dc09480bb0ef125e6de1a7c54f64466475b8ef

2024-09-11 13:48 UTC, Jpcampos123 commented on pages/login/index.vue
> +  const siteKey = config.public.siteKey
atualizado no commit - 22dc09480bb0ef125e6de1a7c54f64466475b8ef

2024-09-11 13:48 UTC, Jpcampos123 commented on pages/login/index.vue
> +    const token = await grecaptcha.execute(siteKey, { action: 'submit' })
atualizado no commit - 22dc09480bb0ef125e6de1a7c54f64466475b8ef

2024-09-11 13:48 UTC, Jpcampos123 commented on pages/register/index.vue
> +  const siteKey = config.public.siteKey
atualizado no commit - 22dc09480bb0ef125e6de1a7c54f64466475b8ef

2024-09-11 13:49 UTC, Jpcampos123 commented on plugins/recaptcha.ts
> +  const srcSiteKey = $config.public.srcSiteKey as string
atualizado no commit - 22dc09480bb0ef125e6de1a7c54f64466475b8ef

2024-09-11 13:49 UTC, Jpcampos123 commented on plugins/recaptcha.ts
> +    script.src = srcSiteKey
atualizado no commit - 22dc09480bb0ef125e6de1a7c54f64466475b8ef

2024-09-11 16:53 UTC, jonatasoli approved these changes
LGTM!

2024-09-11 16:53 UTC, merged