[FRONT] - Update das libs #209
jonatasoli/fast-ecommerce-front pull request #212
Opened 2024-09-24 14:55 UTC by Jpcampos123

build(dependencies): update packages to the most compatible current versions and test

2024-10-04 16:12 UTC, jonatasoli requested changes
Algumas pequenas alerações:
- Tem 2 comentários
- Mudar o nome da PR e completar ela

2024-10-04 19:52 UTC, Jpcampos123 reviewed
código revisado

2024-10-05 19:38 UTC, Jpcampos123 commented on .husky/commit-msg
> -. "$(dirname -- "$0")/_/husky.sh"
estava dando um erro quando eu rodava o yarn lint:fix , porém nesse commit já voltei ele - [7237997](https://github.com/jonatasoli/fast-ecommerce-front/pull/212/commits/7237997660a5180327acab5183c8cd115b6d1db1)

2024-10-05 19:38 UTC, Jpcampos123 commented on composables/useEstimate.ts
> -  const data = ref<IDataCart>()
estava dando um erro quando eu rodava o yarn lint:fix , porém nesse commit já voltei ele - [7237997](https://github.com/jonatasoli/fast-ecommerce-front/pull/212/commits/7237997660a5180327acab5183c8cd115b6d1db1)

2024-10-06 11:41 UTC, jonatasoli approved these changes
LGTM!

2024-10-06 11:41 UTC, merged