Ajuste no cadastro de um novo usuário
jonatasoli/fast-ecommerce-front pull request #232
Opened 2024-10-16 14:35 UTC by Jpcampos123

Adicionada validação ao campo de username para garantir que:

   -  Todas as letras sejam minúsculas.
   -  O campo não contenha caracteres especiais.
   -  Espaços não sejam permitidos no nome de usuário.

2024-10-17 17:04 UTC, jonatasoli commented on pages/cart/index.vue
> +      messageInvalidCEP.value = 'O CEP informado está vazio ou é inválido.'
a mensagem não deveria ficar no i18n?

2024-10-17 17:06 UTC, jonatasoli requested changes
Algumas alterações.

2024-10-17 17:06 UTC, jonatasoli commented on pages/cart/index.vue
> +      validationCEP.value = 'error'
a mensagem n+ao deveria ficar no i18nn?

2024-10-17 17:06 UTC, jonatasoli commented on pages/cart/index.vue
> +      return 'Grátis'
A mesagem não deveria ficar no i18n?

2024-10-17 17:06 UTC, jonatasoli commented on pages/register/index.vue
> +          .regex(/^[a-z0-9]+$/, t('register.formValidation.invalidUsername')) // Apenas letras minúsculas e números, sem espaços ou caracteres especiais
Seria melhor deixar o regex no utils?

2024-10-17 19:00 UTC, Jpcampos123 commented on pages/cart/index.vue
> +      messageInvalidCEP.value = 'O CEP informado está vazio ou é inválido.'
corrigido commit - 62eb9132ada05a83f193bd3e564bb5c772c10e6f

2024-10-17 19:03 UTC, Jpcampos123 commented on pages/cart/index.vue
> +      validationCEP.value = 'error'
a mensagem consegui alterar, já o validationCEP eu iria ter que refatorar o código , pq existe uma validação que só aceita error, success, warning.

` :validation="validationCEP"`

2024-10-17 19:06 UTC, Jpcampos123 commented on pages/register/index.vue
> +          .regex(/^[a-z0-9]+$/, t('register.formValidation.invalidUsername')) // Apenas letras minúsculas e números, sem espaços ou caracteres especiais
o regex é do próprio vee validade/zod, ele não aceita outras funções.

` {
    kind: "regex";
    regex: RegExp;
    message?: string;
}`

2024-10-17 19:11 UTC, Jpcampos123 commented on pages/register/index.vue
> +          .regex(/^[a-z0-9]+$/, t('register.formValidation.invalidUsername')) // Apenas letras minúsculas e números, sem espaços ou caracteres especiais
corrigido commit - https://github.com/jonatasoli/fast-ecommerce-front/commit/62eb9132ada05a83f193bd3e564bb5c772c10e6f

2024-10-18 06:49 UTC, jonatasoli approved these changes
LGTM!

2024-10-18 06:49 UTC, merged